bbox: "40.551042, -74.05663, 40.739446, -73.833365"
usernames:
  - mmann1123
  - haycam
  - I-Izzo
  - isamah
  - livmakesmaps
  - kengaroo5445
  - brikin
  - caitnahc
  - KQWilson
  - o_paq
  - DuckDuckCat
  - ryleeloveshot
  - norabutter

newer_than_date: "2010-12-01"   
